import { ConfiguratorState, ShadeCalculations } from '../types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

export interface SavedQuote {
  id: string;
  reference: string;
  expiresAt: string;
  quoteName: string;
  customerReference?: string | null;
  nameAutoGenerated: boolean;
  accessToken: string;
  shopifyCustomerCreated?: boolean;
  shopifyCustomerId?: string | null;
}

export interface QuoteData {
  id: string;
  quote_reference: string;
  quote_name: string;
  customer_reference?: string | null;
  name_auto_generated: boolean;
  customer_email?: string;
  config_data: ConfiguratorState;
  calculations_data: ShadeCalculations;
  created_at: string;
  expires_at: string;
  status: string;
}


/**
 * Save a quote to the database
 */
export async function saveQuote(
  config: ConfiguratorState,
  calculations: ShadeCalculations,
  email?: string,
  quoteName?: string,
  customerReference?: string
): Promise<SavedQuote> {
  const response = await fetch(`${SUPABASE_URL}/functions/v1/save-quote`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      config,
      calculations,
      email: email || null,
      quoteName: quoteName || null,
      customerReference: customerReference || null,
    }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to save quote');
  }

  return {
    id: data.quote.id,
    reference: data.quote.reference,
    expiresAt: data.quote.expiresAt,
    quoteName: data.quote.quoteName,
    customerReference: data.quote.customerReference,
    nameAutoGenerated: data.quote.nameAutoGenerated,
    accessToken: data.quote.accessToken,
    shopifyCustomerCreated: data.quote.shopifyCustomerCreated,
    shopifyCustomerId: data.quote.shopifyCustomerId,
  };
}

/**
 * Retrieve a quote by ID and access token
 */
export async function getQuoteById(id: string, accessToken: string): Promise<QuoteData> {
  const response = await fetch(
    `${SUPABASE_URL}/functions/v1/save-quote?id=${encodeURIComponent(id)}&token=${encodeURIComponent(accessToken)}`,
    {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
        'Content-Type': 'application/json',
      },
    }
  );

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to retrieve quote');
  }

  return data.quote;
}

/**
 * Update quote status (e.g., mark as completed)
 */
export async function updateQuoteStatus(
  id: string,
  accessToken: string,
  status: 'saved' | 'completed' | 'expired'
): Promise<void> {
  const response = await fetch(`${SUPABASE_URL}/functions/v1/save-quote`, {
    method: 'PATCH',
    headers: {
      'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ id, token: accessToken, status }),
  });

  const data = await response.json();

  if (!data.success) {
    throw new Error(data.error || 'Failed to update quote status');
  }
}

/**
 * Generate a shareable quote URL with access token
 */
export function generateQuoteUrl(quoteId: string, accessToken: string): string {
  const baseUrl = window.location.origin;
  return `${baseUrl}${window.location.pathname}?quote=${quoteId}&token=${encodeURIComponent(accessToken)}`;
}

/**
 * Get quote ID and token from URL if present
 */
export function getQuoteFromUrl(): { id: string; token: string } | null {
  const urlParams = new URLSearchParams(window.location.search);
  const id = urlParams.get('quote');
  const token = urlParams.get('token');

  if (!id || !token) {
    return null;
  }

  return { id, token };
}

/**
 * Format expiration date for display
 */
export function formatExpirationDate(expiresAt: string): string {
  const date = new Date(expiresAt);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

/**
 * Check if quote is expired
 */
export function isQuoteExpired(expiresAt: string): boolean {
  return new Date(expiresAt) < new Date();
}

/**
 * Mark quote as converted to cart
 */
export async function markQuoteConverted(quoteId: string, accessToken: string): Promise<void> {
  await updateQuoteStatus(quoteId, accessToken, 'completed');
}

